[formatting]
line_length = 79

[display]
default_table_page_size = 10
dataframes = "rich"
default_width = "medium"
cell_output = "above"
reference_highlighting = false
default_table_max_columns = 50
code_editor_font_size = 14
theme = "dark"

[mcp]
presets = []

[mcp.mcpServers]

[package_management]
manager = "uv"

[experimental]
inline_ai_tooltip = true
performant_table_charts = true
sql_linter = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[completion]
activate_on_typing = true
copilot = "custom"

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[diagnostics]
enabled = false

[runtime]
reactive_tests = false
auto_instantiate = true
watcher_on_save = "lazy"
on_cell_change = "lazy"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
auto_reload = "lazy"
dotenv = []
default_sql_output = "auto"
default_auto_download = []

[snippets]
custom_paths = []
include_default_snippets = true

[ai]
mode = "manual"
rules = ""
inline_tooltip = false

[ai.models]
custom_models = []
autocomplete_model = "openai/gpt-4.1"
displayed_models = []

[server]
browser = "default"
follow_symlink = false

[language_servers.basedpyright]
enabled = false

[language_servers.pylsp]
enable_pylint = false
enable_ruff = true
enable_mypy = true
enable_pyflakes = false
enable_flake8 = false
enable_pydocstyle = false
enabled = true

[language_servers.ty]
enabled = true
